name: Create and publish a Docker image and update Wiki documentation

on:
  push:
    tags:
      - '*'

jobs:
  create-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set IMAGE_NAME to repo name (lowercase)
        run: echo "IMAGE_NAME=$(basename '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: medicaldataworks.azurecr.io
          username: ${{ secrets.MDW_ACR_USERNAME }}
          password: ${{ secrets.MDW_ACR_PASSWORD }}

      - name: Set up SSH deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LICENCED_REPO_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: medicaldataworks.azurecr.io/strongaya/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          ssh: default

  build-and-push-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert .rst files to Markdown, including index.rst as Home.md
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          mkdir -p converted_md
          find . -name "*.rst" -exec sh -c 'if [ "$(basename {})" = "index.rst" ]; then pandoc -f rst -t markdown -o converted_md/Home.md "{}"; else pandoc -f rst -t markdown -o converted_md/"$(basename {} .rst).md" "{}"; fi' \;
        shell: bash

      - name: Push Documentation to Wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.wiki.git wiki

          rsync -av converted_md/ wiki/

          cd wiki

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to the wiki."
            exit 0
          fi

          git add .
          git commit -m "Update Wiki documentation by ${{ github.actor }}"
          git push
        shell: bash